# Generated by Django 3.2.5 on 2021-07-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_thinq24', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.FileField(blank=True, upload_to='blog_image'),
        ),
    ]
